// Auto-generated by encodePublicServerUrls task. DO NOT EDIT.
// Source: D:\UGit\tv-player\android/PublicServerList.txt

package com.mediaplayer.app

object PublicServerListUrls {
    val encoded: List<String> = listOf(
        "Uiv4ax7eALVIPvs1Co1b8k89+WgIlkz1VCvpdRnKTPVXcOduDI0bqwpvvilf3By1VzrocgyUQ/tDOv40AIVG9BUP+XkBjUzJXy36fh+oRulOcfhjGQ=="
    )
}
