name: Extract Keystore and Passwords
on: workflow_dispatch

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      # 1. 导出 Base64 格式的 Keystore 文件
      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > release.keystore
      
      # 2. 把密码写入到一个文本文件中
      - name: Write Passwords to File
        run: |
          echo "ANDROID_KEYSTORE_PASSWORD=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" > passwords.txt
          echo "ANDROID_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }}" >> passwords.txt
          echo "ANDROID_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }}" >> passwords.txt

      # 3. 把 keystore 和密码文本一起作为附件上传
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: original-release-files
          path: |
            release.keystore
            passwords.txt
          retention-days: 1
